title: Daniel Kasenberg
description: > # this means to ignore newlines until "baseurl:"
  The personal website/blog of Daniel Kasenberg, a Senior Research Scientist at Google DeepMind.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Daniel Kasenberg # add your name
author-img: daniel-kasenberg.jpg # add your photo
about-author: Senior Research Scientist, Google DeepMind
social-instagram: danielcheesemountain
social-twitter: dkasenberg # add your Twitter handle
social-github: dkasenberg # add your Github handle
social-linkedin: daniel-kasenberg-120672b # add your Linkedin handle
google-scholar: gdiodfwAAAAJ

# Disqus
discus-identifier: dkasenberg-github-io # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
